#!/bin/bash
#
# Create API Tokens for Organization Admin Users
#
# This script creates API tokens for organization admin users created by create-org-admins.sh
# and generates an org.txt file ready to use with org-migration.sh
#
# Usage:
#   ./create-org-tokens.sh [--target]
#
# Options:
#   --target    Create tokens on target AAP instead of source
#
# Prerequisites:
#   - SOURCE_AAP_URL or TARGET_AAP_URL in .env
#   - Admin credentials (username/password)
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Parse arguments
USE_TARGET=false
if [[ "$1" == "--target" ]]; then
    USE_TARGET=true
    shift
fi

# Load .env if it exists
if [[ -f .env ]]; then
    echo -e "${BLUE}→${NC} Loading configuration from .env"
    export $(grep -v '^#' .env | grep -E 'SOURCE_AAP_URL|SOURCE_AAP_TOKEN|TARGET_AAP_URL|TARGET_AAP_TOKEN' | xargs)
fi

# Determine which AAP to use
if [[ "$USE_TARGET" == "true" ]]; then
    AAP_URL="${TARGET_AAP_URL}"
    AAP_TOKEN="${TARGET_AAP_TOKEN}"
    AAP_TYPE="Target"
else
    AAP_URL="${SOURCE_AAP_URL}"
    AAP_TOKEN="${SOURCE_AAP_TOKEN}"
    AAP_TYPE="Source"
fi

if [[ -z "$AAP_URL" ]] || [[ -z "$AAP_TOKEN" ]]; then
    echo -e "${RED}❌ Error: AAP URL and TOKEN not set${NC}"
    if [[ "$USE_TARGET" == "true" ]]; then
        echo "Set TARGET_AAP_URL and TARGET_AAP_TOKEN in .env"
    else
        echo "Set SOURCE_AAP_URL and SOURCE_AAP_TOKEN in .env"
    fi
    exit 1
fi

# Strip /api/v2 suffix if present in AAP_URL
BASE_URL="${AAP_URL%/api/v2}"
BASE_URL="${BASE_URL%/}"  # Remove trailing slash if any
API_BASE="${BASE_URL}/api/v2"
PASSWORD="ansible123"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Create Organization Admin Tokens${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "${AAP_TYPE} AAP: ${AAP_URL}"
echo "User password: ${PASSWORD}"
echo "Output: org.txt"
echo ""

# Backup existing org.txt
if [[ -f org.txt ]]; then
    BACKUP="org.txt.backup.$(date +%Y%m%d_%H%M%S)"
    echo -e "${YELLOW}→${NC} Backing up existing org.txt to ${BACKUP}"
    cp org.txt "$BACKUP"
fi

# Create new org.txt
cat > org.txt << 'HEADER'
# Organization Token Mapping
# Format: organization_name=api_token
# Generated by create-org-tokens.sh

HEADER

echo -e "${YELLOW}→${NC} Fetching organizations..."
ORGS_JSON=$(curl -sk -H "Authorization: Bearer ${AAP_TOKEN}" \
    "${API_BASE}/organizations/?page_size=200" 2>/dev/null | jq -r '.results')

if [[ -z "$ORGS_JSON" ]] || [[ "$ORGS_JSON" == "null" ]]; then
    echo -e "${RED}❌ Failed to fetch organizations${NC}"
    echo "Make sure ${AAP_TYPE}_AAP_TOKEN is set correctly in .env"
    exit 1
fi

ORG_COUNT=$(echo "$ORGS_JSON" | jq '. | length')
echo -e "${GREEN}✓${NC} Found ${ORG_COUNT} organizations"
echo ""

CREATED=0
SKIPPED=0
FAILED=0

while read -r org; do
    ORG_ID=$(echo "$org" | jq -r '.id')
    ORG_NAME=$(echo "$org" | jq -r '.name')

    # Skip Default organization
    if [[ "$ORG_NAME" == "Default" ]]; then
        echo -e "${BLUE}⏭️  Skipping Default organization${NC}"
        echo "# Default=<use_system_admin_token>" >> org.txt
        ((SKIPPED++)) || true
        continue
    fi

    # Generate username
    USERNAME="admin_$(echo "$ORG_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g')"

    echo -e "${YELLOW}→${NC} Processing: ${ORG_NAME}"
    echo "   Username: ${USERNAME}"

    # Get user ID by searching for username
    USER_JSON=$(curl -sk -u "${USERNAME}:${PASSWORD}" \
        "${API_BASE}/users/?username=${USERNAME}" 2>/dev/null)

    USER_ID=$(echo "$USER_JSON" | jq -r '.results[0].id // empty')

    if [[ -z "$USER_ID" ]]; then
        echo -e "${RED}   ❌ Failed to authenticate as ${USERNAME}${NC}"
        echo "# ${ORG_NAME}=<user_not_found_or_auth_failed>" >> org.txt
        ((FAILED++)) || true
        echo ""
        continue
    fi

    echo -e "${GREEN}   ✓ Authenticated (User ID: ${USER_ID})${NC}"

    # Create personal token
    echo "   → Creating API token..."

    TOKEN_DATA=$(cat <<EOF
{
    "description": "Organization migration token for ${ORG_NAME}",
    "application": null,
    "scope": "write"
}
EOF
)

    TOKEN_RESPONSE=$(curl -sk -u "${USERNAME}:${PASSWORD}" \
        -X POST \
        -H "Content-Type: application/json" \
        "${API_BASE}/users/${USER_ID}/personal_tokens/" \
        -d "$TOKEN_DATA" 2>/dev/null)

    TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.token // empty')

    if [[ -z "$TOKEN" ]]; then
        echo -e "${RED}   ❌ Failed to create token${NC}"

        # Check if token already exists
        EXISTING_TOKENS=$(curl -sk -u "${USERNAME}:${PASSWORD}" \
            "${API_BASE}/users/${USER_ID}/personal_tokens/" 2>/dev/null | jq -r '.results[] | select(.description | contains("migration")) | .id')

        if [[ -n "$EXISTING_TOKENS" ]]; then
            echo -e "${YELLOW}   ⚠️  Existing migration token found${NC}"
            echo "# ${ORG_NAME}=<token_exists_get_from_aap_ui>" >> org.txt
        else
            echo "# ${ORG_NAME}=<token_creation_failed>" >> org.txt
        fi

        ((FAILED++)) || true
        echo ""
        continue
    fi

    echo -e "${GREEN}   ✓ Token created${NC}"

    # Sanitize org name for file (replace spaces with underscores)
    ORG_FILE_NAME=$(echo "$ORG_NAME" | sed 's/[^a-zA-Z0-9]/_/g')

    # Add to org.txt
    echo "${ORG_FILE_NAME}=${TOKEN}" >> org.txt

    ((CREATED++)) || true
    echo ""
done < <(echo "$ORGS_JSON" | jq -c '.[]')

echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}✓ Process Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Summary:"
echo "  Created: ${CREATED} tokens"
echo "  Skipped: ${SKIPPED}"
echo "  Failed: ${FAILED}"
echo ""
echo "Output file: org.txt"
echo ""

if [[ ${CREATED} -gt 0 ]]; then
    echo -e "${GREEN}✓ Ready to use with org-migration.sh!${NC}"
    echo ""
    echo "Example usage:"
    echo "  ./org-migration.sh --organization $(head -5 org.txt | grep -v '^#' | head -1 | cut -d= -f1) migrate -r organizations"
fi

echo ""
