"""initial state schema

Revision ID: b8e1e6f93880
Revises:
Create Date: 2026-08-10 19:41:35.644649

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8e1e6f93880"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkpoints",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "checkpoint_name",
            sa.String(length=255),
            nullable=False,
            comment="Unique name for this checkpoint",
        ),
        sa.Column(
            "migration_id",
            sa.String(length=255),
            nullable=False,
            comment="Migration run identifier (UUID or timestamp)",
        ),
        sa.Column(
            "phase",
            sa.String(length=50),
            nullable=False,
            comment="Migration phase at checkpoint (e.g., inventories, hosts)",
        ),
        sa.Column(
            "progress_stats",
            sa.JSON(),
            nullable=False,
            comment="Progress statistics (total, completed, failed counts)",
        ),
        sa.Column(
            "checkpoint_data",
            sa.JSON(),
            nullable=False,
            comment="Additional checkpoint data (last processed ID, batch info, etc.)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When checkpoint was created",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Human-readable description of checkpoint",
        ),
        sa.Column(
            "checksum",
            sa.String(length=64),
            nullable=True,
            comment="SHA-256 checksum for integrity validation",
        ),
        sa.Column(
            "is_valid",
            sa.Boolean(),
            nullable=False,
            comment="Whether checkpoint is valid and can be restored",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_created_at_desc", "checkpoints", ["created_at"], unique=False, postgresql_using="btree"
    )
    op.create_index(
        "idx_migration_id_phase", "checkpoints", ["migration_id", "phase"], unique=False
    )
    op.create_index(
        op.f("ix_checkpoints_checkpoint_name"), "checkpoints", ["checkpoint_name"], unique=True
    )
    op.create_index(op.f("ix_checkpoints_created_at"), "checkpoints", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_checkpoints_migration_id"), "checkpoints", ["migration_id"], unique=False
    )
    op.create_table(
        "migration_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "migration_id",
            sa.String(length=255),
            nullable=False,
            comment="Unique migration run identifier (UUID)",
        ),
        sa.Column(
            "migration_name",
            sa.String(length=255),
            nullable=True,
            comment="Human-readable migration name",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Overall migration status: in_progress, completed, failed, paused",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When migration started",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(),
            nullable=True,
            comment="When migration completed or failed",
        ),
        sa.Column(
            "last_checkpoint_at",
            sa.DateTime(),
            nullable=True,
            comment="When last checkpoint was created",
        ),
        sa.Column(
            "config_snapshot",
            sa.JSON(),
            nullable=False,
            comment="Configuration snapshot (sanitized, no secrets)",
        ),
        sa.Column(
            "source_url", sa.String(length=512), nullable=False, comment="Source AAP 2.3 URL"
        ),
        sa.Column(
            "target_url", sa.String(length=512), nullable=False, comment="Target AAP 2.6 URL"
        ),
        sa.Column(
            "total_resources",
            sa.Integer(),
            nullable=False,
            comment="Total number of resources to migrate",
        ),
        sa.Column(
            "completed_resources",
            sa.Integer(),
            nullable=False,
            comment="Number of successfully migrated resources",
        ),
        sa.Column(
            "failed_resources", sa.Integer(), nullable=False, comment="Number of failed resources"
        ),
        sa.Column(
            "skipped_resources", sa.Integer(), nullable=False, comment="Number of skipped resources"
        ),
        sa.Column(
            "environment",
            sa.JSON(),
            nullable=True,
            comment="Environment information (Python version, OS, etc.)",
        ),
        sa.Column(
            "notes", sa.Text(), nullable=True, comment="Additional notes about the migration"
        ),
        sa.CheckConstraint(
            "status IN ('in_progress', 'completed', 'failed', 'paused')",
            name="ck_migration_metadata_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_started_at_desc",
        "migration_metadata",
        ["started_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        op.f("ix_migration_metadata_migration_id"),
        "migration_metadata",
        ["migration_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_migration_metadata_started_at"), "migration_metadata", ["started_at"], unique=False
    )
    op.create_index(
        op.f("ix_migration_metadata_status"), "migration_metadata", ["status"], unique=False
    )
    op.create_table(
        "migration_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "resource_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of resource (e.g., inventory, host, credential)",
        ),
        sa.Column(
            "source_id", sa.BigInteger(), nullable=False, comment="ID in source AAP 2.3 system"
        ),
        sa.Column(
            "source_key",
            sa.String(length=128),
            server_default="",
            nullable=False,
            comment="Plan source / connection scope key (empty for single-source)",
        ),
        sa.Column(
            "source_name",
            sa.String(length=512),
            nullable=False,
            comment="Name of resource in source system",
        ),
        sa.Column(
            "target_id",
            sa.BigInteger(),
            nullable=True,
            comment="ID in target AAP 2.6 system (null if not yet migrated)",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Migration status: pending, in_progress, completed, failed, skipped",
        ),
        sa.Column(
            "phase",
            sa.String(length=50),
            nullable=False,
            comment="Migration phase (e.g., export, transform, import)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When record was last updated",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(),
            nullable=True,
            comment="When migration started for this resource",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(),
            nullable=True,
            comment="When migration completed for this resource",
        ),
        sa.Column(
            "error_message", sa.Text(), nullable=True, comment="Error message if migration failed"
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False, comment="Number of retry attempts"),
        sa.CheckConstraint(
            "status IN ('pending', 'in_progress', 'completed', 'failed', 'skipped')",
            name="ck_migration_progress_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_key", "resource_type", "source_id", name="uq_progress_source_key_type_id"
        ),
    )
    op.create_index("idx_created_at", "migration_progress", ["created_at"], unique=False)
    op.create_index(
        "idx_resource_type_status", "migration_progress", ["resource_type", "status"], unique=False
    )
    op.create_index("idx_status_phase", "migration_progress", ["status", "phase"], unique=False)
    op.create_index(
        op.f("ix_migration_progress_phase"), "migration_progress", ["phase"], unique=False
    )
    op.create_index(
        op.f("ix_migration_progress_resource_type"),
        "migration_progress",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_migration_progress_source_id"), "migration_progress", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_migration_progress_source_key"), "migration_progress", ["source_key"], unique=False
    )
    op.create_index(
        op.f("ix_migration_progress_status"), "migration_progress", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_migration_progress_target_id"), "migration_progress", ["target_id"], unique=False
    )
    op.create_table(
        "performance_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "migration_id",
            sa.String(length=255),
            nullable=False,
            comment="Migration run identifier",
        ),
        sa.Column(
            "metric_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of metric (e.g., api_call, batch_processing, checkpoint)",
        ),
        sa.Column(
            "resource_type",
            sa.String(length=50),
            nullable=True,
            comment="Resource type being measured (if applicable)",
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When metric was recorded",
        ),
        sa.Column("duration_ms", sa.Float(), nullable=True, comment="Duration in milliseconds"),
        sa.Column(
            "throughput", sa.Float(), nullable=True, comment="Throughput (resources per second)"
        ),
        sa.Column(
            "batch_size", sa.Integer(), nullable=True, comment="Batch size used (if applicable)"
        ),
        sa.Column(
            "success_count", sa.Integer(), nullable=False, comment="Number of successful operations"
        ),
        sa.Column(
            "failure_count", sa.Integer(), nullable=False, comment="Number of failed operations"
        ),
        sa.Column(
            "metric_data",
            sa.JSON(),
            nullable=True,
            comment="Additional metric data (memory usage, API calls, etc.)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_metric_type_recorded_at",
        "performance_metrics",
        ["metric_type", "recorded_at"],
        unique=False,
    )
    op.create_index(
        "idx_migration_id_metric_type",
        "performance_metrics",
        ["migration_id", "metric_type"],
        unique=False,
    )
    op.create_index(
        "idx_recorded_at_desc",
        "performance_metrics",
        ["recorded_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        op.f("ix_performance_metrics_metric_type"),
        "performance_metrics",
        ["metric_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_performance_metrics_migration_id"),
        "performance_metrics",
        ["migration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_performance_metrics_recorded_at"),
        "performance_metrics",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_performance_metrics_resource_type"),
        "performance_metrics",
        ["resource_type"],
        unique=False,
    )
    op.create_table(
        "id_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "resource_type", sa.String(length=50), nullable=False, comment="Type of resource"
        ),
        sa.Column(
            "source_id", sa.BigInteger(), nullable=False, comment="ID in source AAP 2.3 system"
        ),
        sa.Column(
            "source_key",
            sa.String(length=128),
            server_default="",
            nullable=False,
            comment="Plan source / connection scope key (empty for single-source)",
        ),
        sa.Column(
            "target_id",
            sa.BigInteger(),
            nullable=True,
            comment="ID in target AAP 2.6 system (null if not yet imported)",
        ),
        sa.Column(
            "source_name",
            sa.String(length=512),
            nullable=True,
            comment="Name of resource in source system",
        ),
        sa.Column(
            "target_name",
            sa.String(length=512),
            nullable=True,
            comment="Name of resource in target system",
        ),
        sa.Column("migration_progress_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When mapping was created",
        ),
        sa.Column(
            "mapping_metadata",
            sa.JSON(),
            nullable=True,
            comment="Additional metadata about the mapping",
        ),
        sa.ForeignKeyConstraint(
            ["migration_progress_id"], ["migration_progress.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_key", "resource_type", "source_id", name="uq_mapping_source_key_type_id"
        ),
    )
    op.create_index(
        "idx_resource_type_target_id", "id_mappings", ["resource_type", "target_id"], unique=False
    )
    op.create_index(
        "idx_source_id_target_id", "id_mappings", ["source_id", "target_id"], unique=False
    )
    op.create_index(
        op.f("ix_id_mappings_migration_progress_id"),
        "id_mappings",
        ["migration_progress_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_id_mappings_resource_type"), "id_mappings", ["resource_type"], unique=False
    )
    op.create_index(op.f("ix_id_mappings_source_id"), "id_mappings", ["source_id"], unique=False)
    op.create_index(op.f("ix_id_mappings_source_key"), "id_mappings", ["source_key"], unique=False)
    op.create_index(op.f("ix_id_mappings_target_id"), "id_mappings", ["target_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_id_mappings_target_id"), table_name="id_mappings")
    op.drop_index(op.f("ix_id_mappings_source_key"), table_name="id_mappings")
    op.drop_index(op.f("ix_id_mappings_source_id"), table_name="id_mappings")
    op.drop_index(op.f("ix_id_mappings_resource_type"), table_name="id_mappings")
    op.drop_index(op.f("ix_id_mappings_migration_progress_id"), table_name="id_mappings")
    op.drop_index("idx_source_id_target_id", table_name="id_mappings")
    op.drop_index("idx_resource_type_target_id", table_name="id_mappings")
    op.drop_table("id_mappings")
    op.drop_index(op.f("ix_performance_metrics_resource_type"), table_name="performance_metrics")
    op.drop_index(op.f("ix_performance_metrics_recorded_at"), table_name="performance_metrics")
    op.drop_index(op.f("ix_performance_metrics_migration_id"), table_name="performance_metrics")
    op.drop_index(op.f("ix_performance_metrics_metric_type"), table_name="performance_metrics")
    op.drop_index(
        "idx_recorded_at_desc", table_name="performance_metrics", postgresql_using="btree"
    )
    op.drop_index("idx_migration_id_metric_type", table_name="performance_metrics")
    op.drop_index("idx_metric_type_recorded_at", table_name="performance_metrics")
    op.drop_table("performance_metrics")
    op.drop_index(op.f("ix_migration_progress_target_id"), table_name="migration_progress")
    op.drop_index(op.f("ix_migration_progress_status"), table_name="migration_progress")
    op.drop_index(op.f("ix_migration_progress_source_key"), table_name="migration_progress")
    op.drop_index(op.f("ix_migration_progress_source_id"), table_name="migration_progress")
    op.drop_index(op.f("ix_migration_progress_resource_type"), table_name="migration_progress")
    op.drop_index(op.f("ix_migration_progress_phase"), table_name="migration_progress")
    op.drop_index("idx_status_phase", table_name="migration_progress")
    op.drop_index("idx_resource_type_status", table_name="migration_progress")
    op.drop_index("idx_created_at", table_name="migration_progress")
    op.drop_table("migration_progress")
    op.drop_index(op.f("ix_migration_metadata_status"), table_name="migration_metadata")
    op.drop_index(op.f("ix_migration_metadata_started_at"), table_name="migration_metadata")
    op.drop_index(op.f("ix_migration_metadata_migration_id"), table_name="migration_metadata")
    op.drop_index("idx_started_at_desc", table_name="migration_metadata", postgresql_using="btree")
    op.drop_table("migration_metadata")
    op.drop_index(op.f("ix_checkpoints_migration_id"), table_name="checkpoints")
    op.drop_index(op.f("ix_checkpoints_created_at"), table_name="checkpoints")
    op.drop_index(op.f("ix_checkpoints_checkpoint_name"), table_name="checkpoints")
    op.drop_index("idx_migration_id_phase", table_name="checkpoints")
    op.drop_index("idx_created_at_desc", table_name="checkpoints", postgresql_using="btree")
    op.drop_table("checkpoints")
    # ### end Alembic commands ###
