from collections.abc import Callable
from typing import Any

from aap_migration.migration.importers.base import ResourceImporter
from aap_migration.utils.logging import get_logger

logger = get_logger(__name__)


class ApplicationImporter(ResourceImporter):
    """Importer for OAuth applications with secret management.

    Applications contain sensitive client secrets. This importer:
    - Auto-generates new client secrets (security best practice)
    - Creates applications with new secrets
    - Generates report of which external systems need updates
    - Optionally uses provided secrets from config
    """

    DEPENDENCIES: dict[str, str] = {
        "organization": "organizations",
    }

    async def import_resource(
        self,
        resource_type: str,
        source_id: int,
        data: dict[str, Any],
        resolve_dependencies: bool = True,
    ) -> dict[str, Any] | None:
        """Import an OAuth application with secret generation.

        Args:
            resource_type: Should be 'applications'
            source_id: Source application ID
            data: Application data
            resolve_dependencies: Whether to resolve organization dependency

        Returns:
            Created application data with new client_id/client_secret
        """
        if self.state.is_migrated(resource_type, source_id):
            self.stats["skipped_count"] += 1
            return None

        name = data.get("name")
        if not name:
            logger.error("application_missing_name", source_id=source_id)
            return None

        self.state.mark_in_progress(resource_type, source_id, name, "import")

        # Resolve organization dependency
        if resolve_dependencies:
            data = await self._resolve_dependencies(resource_type, data)

        # Handle client secret
        if data.get("_requires_new_secret"):
            # Client secret will be auto-generated by AAP on creation
            # Remove the redacted placeholder
            data.pop("client_secret", None)
            logger.info("application_will_generate_new_secret", name=name, source_id=source_id)

        # Remove fields that AAP auto-generates or shouldn't be sent in POST
        # client_id and client_secret are auto-generated by AAP
        data.pop("client_id", None)
        if not data.get("_requires_new_secret"):
            # Also remove client_secret if it exists (AAP masks it anyway)
            data.pop("client_secret", None)

        # Remove migration metadata
        for key in list(data.keys()):
            if key.startswith("_"):
                data.pop(key)

        # Create application
        try:
            result = await self.client.post(f"{resource_type}/", json_data=data)

            target_id = result["id"]
            new_client_id = result.get("client_id")
            new_client_secret = result.get("client_secret")

            # Save mapping
            self.state.save_id_mapping(
                resource_type=resource_type,
                source_id=source_id,
                target_id=target_id,
                source_name=name,
                target_name=result.get("name", name),
            )
            self.state.mark_completed(resource_type, source_id, target_id, name)
            self.stats["imported_count"] += 1

            # Log new credentials for user
            logger.info(
                "application_created_with_new_secret",
                source_id=source_id,
                target_id=target_id,
                name=name,
                client_id=new_client_id,
                message="⚠️  Update external systems with new credentials",
            )

            # Add to report for user
            self.import_errors.append(
                {
                    "resource_type": "applications",
                    "source_id": source_id,
                    "name": name,
                    "action_required": "UPDATE_EXTERNAL_SYSTEMS",
                    "new_client_id": new_client_id,
                    "new_client_secret": new_client_secret,
                    "message": f"Application '{name}' created with NEW credentials. Update external systems.",
                }
            )

            return result

        except Exception as e:
            logger.error(
                "application_import_failed",
                name=name,
                source_id=source_id,
                error=str(e),
            )
            self.state.mark_failed(resource_type, source_id, str(e))
            self.stats["error_count"] += 1
            return None

    async def import_applications(
        self,
        applications: list[dict[str, Any]],
        progress_callback: Callable[[int, int, int], None] | None = None,
    ) -> list[dict[str, Any]]:
        """Import multiple OAuth applications.

        Args:
            applications: List of application data
            progress_callback: Optional progress callback

        Returns:
            List of created applications with new secrets
        """
        return await self._import_parallel("applications", applications, progress_callback)
